### ISSUE TITLE
import `ctc` dependency not found in pyproject.toml

### ISSUE THREAD

**Issue by Evan-Kim2028** [sslivkoff/polars_evm#1]
### Problem
An external package `ctc` is used in `encoding_conversions.py` https://github.com/sslivkoff/polars_evm/blob/5fde903620feff17289a94e11fdd4b9935a5c9a8/polars_evm/_helpers/encoding_conversions.py#L7

This was preventing the evm space from automatically registering for me. It does not appear that `ctc` is a pyproject dependency. After I installed `ctc` separately, the problem was solved.

**Comment by sslivkoff** [comment]
fixed in fd66438 and new version pushed to pypi
